// resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.jsx
import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import TextInput from '@/Components/TextInput';
import { Link, useForm, usePage } from '@inertiajs/react';
import { Transition } from '@headlessui/react';

export default function UpdateProfileInformation({ mustVerifyEmail, status, admin, allCategorias, className = '' }) {
    const user = usePage().props.auth.user;

    const { data, setData, patch, errors, processing, recentlySuccessful } = useForm({
        name: user.name,
        email: user.email,
        telefono: admin?.telefono || '',
        categorias_ids: admin?.categorias?.map(cat => cat.id) || [],
    });

    const submit = (e) => {
        e.preventDefault();
        patch(route('profile.update'));
    };

    // Manejador manual para los checkboxes (React no tiene v-model)
    const handleCategoryChange = (id) => {
        let newIds = [...data.categorias_ids];
        if (newIds.includes(id)) {
            newIds = newIds.filter(catId => catId !== id);
        } else {
            newIds.push(id);
        }
        setData('categorias_ids', newIds);
    };

    return (
        <section className={className}>
            <header>
                <h2 className="text-lg font-medium text-gray-900 dark:text-gray-100">
                    Profile Information
                </h2>
                <p className="mt-1 text-sm text-gray-600 dark:text-gray-400">
                    Update your account's profile information and email address.
                </p>
            </header>

            <form onSubmit={submit} className="mt-6 space-y-6">
                <div>
                    <InputLabel htmlFor="name" value="Name" />
                    <TextInput
                        id="name"
                        className="mt-1 block w-full"
                        value={data.name}
                        onChange={(e) => setData('name', e.target.value)}
                        required
                        isFocused
                        autoComplete="name"
                    />
                    <InputError className="mt-2" message={errors.name} />
                </div>

                <div>
                    <InputLabel htmlFor="email" value="Email" />
                    <TextInput
                        id="email"
                        type="email"
                        className="mt-1 block w-full"
                        value={data.email}
                        onChange={(e) => setData('email', e.target.value)}
                        required
                        autoComplete="username"
                    />
                    <InputError className="mt-2" message={errors.email} />
                </div>

                {mustVerifyEmail && user.email_verified_at === null && (
                    <div>
                        <p className="mt-2 text-sm text-gray-800 dark:text-gray-200">
                            Your email address is unverified.
                            <Link
                                href={route('verification.send')}
                                method="post"
                                as="button"
                                className="rounded-md text-sm text-gray-600 underline hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 dark:text-gray-400 dark:hover:text-gray-100 dark:focus:ring-offset-gray-800"
                            >
                                Click here to re-send the verification email.
                            </Link>
                        </p>
                        {status === 'verification-link-sent' && (
                            <div className="mt-2 text-sm font-medium text-green-600 dark:text-green-400">
                                A new verification link has been sent to your email address.
                            </div>
                        )}
                    </div>
                )}

                <div>
                    <InputLabel htmlFor="telefono" value="Teléfono" />
                    <TextInput
                        id="telefono"
                        type="text"
                        className="mt-1 block w-full"
                        value={data.telefono}
                        onChange={(e) => setData('telefono', e.target.value)}
                        required
                    />
                    <InputError className="mt-2" message={errors.telefono} />
                </div>

                <div>
                    <InputLabel value="Mis Categorías" />
                    <div className="grid grid-cols-2 gap-2 mt-2">
                        {allCategorias?.map((cat) => (
                            <div key={cat.id} className="flex items-center">
                                <input
                                    type="checkbox"
                                    id={`edit-cat-${cat.id}`}
                                    value={cat.id}
                                    checked={data.categorias_ids.includes(cat.id)}
                                    onChange={() => handleCategoryChange(cat.id)}
                                    className="rounded dark:bg-gray-900 border-gray-300 text-indigo-600 shadow-sm"
                                />
                                <label 
                                    htmlFor={`edit-cat-${cat.id}`} 
                                    className="ml-2 text-sm text-gray-600 dark:text-gray-400 cursor-pointer"
                                >
                                    {cat.nombre}
                                </label>
                            </div>
                        ))}
                    </div>
                    <InputError className="mt-2" message={errors.categorias_ids} />
                </div>

                <div className="flex items-center gap-4">
                    <PrimaryButton disabled={processing}>Save</PrimaryButton>

                    <Transition
                        show={recentlySuccessful}
                        enter="transition ease-in-out"
                        enterFrom="opacity-0"
                        leave="transition ease-in-out"
                        leaveTo="opacity-0"
                    >
                        <p className="text-sm text-gray-600 dark:text-gray-400">
                            Saved.
                        </p>
                    </Transition>
                </div>
            </form>
        </section>
    );
}

// resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue
<script setup>
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import { Link, useForm, usePage } from '@inertiajs/vue3';

const props = defineProps({
    mustVerifyEmail: { type: Boolean },
    status: { type: String },
    admin: { type: Object },
    allCategorias: { type: Array }, 
});

const user = usePage().props.auth.user;

const form = useForm({
    name: user.name,
    email: user.email,
    telefono: props.admin?.telefono || '',
    categorias_ids: props.admin?.categorias?.map(cat => cat.id) || [],
});
</script>

<template>
    <section>
        <header>
            <h2 class="text-lg font-medium text-gray-900 dark:text-gray-100">
                Profile Information
            </h2>

            <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">
                Update your account's profile information and email address.
            </p>
        </header>

        <form
            @submit.prevent="form.patch(route('profile.update'))"
            class="mt-6 space-y-6"
        >
            <div>
                <InputLabel for="name" value="Name" />

                <TextInput
                    id="name"
                    type="text"
                    class="mt-1 block w-full"
                    v-model="form.name"
                    required
                    autofocus
                    autocomplete="name"
                />

                <InputError class="mt-2" :message="form.errors.name" />
            </div>

            <div>
                <InputLabel for="email" value="Email" />

                <TextInput
                    id="email"
                    type="email"
                    class="mt-1 block w-full"
                    v-model="form.email"
                    required
                    autocomplete="username"
                />

                <InputError class="mt-2" :message="form.errors.email" />
            </div>

            <div v-if="mustVerifyEmail && user.email_verified_at === null">
                <p class="mt-2 text-sm text-gray-800 dark:text-gray-200">
                    Your email address is unverified.
                    <Link
                        :href="route('verification.send')"
                        method="post"
                        as="button"
                        class="rounded-md text-sm text-gray-600 underline hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 dark:text-gray-400 dark:hover:text-gray-100 dark:focus:ring-offset-gray-800"
                    >
                        Click here to re-send the verification email.
                    </Link>
                </p>

                <div
                    v-show="status === 'verification-link-sent'"
                    class="mt-2 text-sm font-medium text-green-600 dark:text-green-400"
                >
                    A new verification link has been sent to your email address.
                </div>
            </div>

            <div class="mt-4">
    <InputLabel for="telefono" value="Teléfono" />
    <TextInput
        id="telefono"
        type="text"
        class="mt-1 block w-full"
        v-model="form.telefono"
        required
    />
    <InputError class="mt-2" :message="form.errors.telefono" />
</div>

<div class="mt-4">
    <InputLabel value="Mis Categorías" />
    <div class="grid grid-cols-2 gap-2 mt-2">
        <div v-for="cat in allCategorias" :key="cat.id" class="flex items-center">
            <input 
                type="checkbox" 
                :id="'edit-cat-' + cat.id"
                :value="cat.id" 
                v-model="form.categorias_ids" 
                class="rounded dark:bg-gray-900 border-gray-300 text-indigo-600 shadow-sm"
            />
            <label :for="'edit-cat-' + cat.id" class="ml-2 text-sm text-gray-600 dark:text-gray-400">
                {{ cat.nombre }}
            </label>
        </div>
    </div>
    <InputError class="mt-2" :message="form.errors.categorias_ids" />
</div>

            <div class="flex items-center gap-4">
                <PrimaryButton :disabled="form.processing">Save</PrimaryButton>

                <Transition
                    enter-active-class="transition ease-in-out"
                    enter-from-class="opacity-0"
                    leave-active-class="transition ease-in-out"
                    leave-to-class="opacity-0"
                >
                    <p
                        v-if="form.recentlySuccessful"
                        class="text-sm text-gray-600 dark:text-gray-400"
                    >
                        Saved.
                    </p>
                </Transition>
            </div>
        </form>
    </section>
</template>
