// resources/js/Pages/Dashboard.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head } from '@inertiajs/vue3';

const props = defineProps({
    admins: Array
});
</script>

<template>
    <Head title="Dashboard" />

    <AuthenticatedLayout>
        <template #header>
            <h2 class="text-xl font-semibold leading-tight text-gray-800 dark:text-gray-200">
                Dashboard - Lista de Administradores
            </h2>
        </template>

        <div class="py-12">
            <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
                <div class="overflow-hidden bg-white shadow-sm sm:rounded-lg dark:bg-gray-800">
                    <div class="p-6 text-gray-900 dark:text-gray-100">
                        
                        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
                            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                                    <tr>
                                        <th scope="col" class="px-6 py-3">Nombre</th>
                                        <th scope="col" class="px-6 py-3">Email</th>
                                        <th scope="col" class="px-6 py-3">Teléfono</th>
                                        <th scope="col" class="px-6 py-3">Categorías</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr v-for="admin in admins" :key="admin.id" class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                                        <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                            {{ admin.nombre }}
                                        </td>
                                        <td class="px-6 py-4">
                                            {{ admin.user?.email }}
                                        </td>
                                        <td class="px-6 py-4">
                                            {{ admin.telefono }}
                                        </td>
                                        <td class="px-6 py-4">
                                            <div class="flex flex-wrap gap-1">
                                                <span v-for="cat in admin.categorias" :key="cat.id" 
                                                    class="px-2 py-1 text-xs font-semibold text-blue-800 bg-blue-100 rounded dark:bg-blue-900 dark:text-blue-300">
                                                    {{ cat.nombre }}
                                                </span>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        </div>
                </div>
            </div>
        </div>
    </AuthenticatedLayout>
</template>

// resources/js/Pages/Dashboard.jsx
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head } from '@inertiajs/react';
import '../../css/mensajes.css';

export default function Dashboard({ mensajes }) {
    return (
        <AuthenticatedLayout
            header={
                <h2 className="text-xl font-semibold leading-tight text-gray-800 dark:text-gray-200">
                    Dashboard
                </h2>
            }
        >
            <Head title="Dashboard" />

            <div className="py-12">
                <div className="mx-auto max-w-7xl sm:px-6 lg:px-8">
                    <div className="overflow-hidden bg-white shadow-sm sm:rounded-lg dark:bg-gray-800">
                        <div className="p-6 text-gray-900 dark:text-gray-100">
                            <h1 className="text-lg font-semibold mb-4">Mensajes disponibles</h1>
                            <div id="containerTable">
                                <table>
                                <thead>
                                    <tr>
                                        <th>Resumen</th>
                                        <th>Prioridad</th>
                                        <th>Requiere Revision</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                        {mensajes && mensajes.length > 0 ? (
                                                mensajes.map((mensaje, index) => (
                                                    <tr key={index}>
                                                        <td> {mensaje.resumen} </td>
                                                        <td> {mensaje.prioridad} </td>
                                                        <td> {mensaje.requiere_revision} </td>
                                                    </tr>
                                                ))
                                        ) : (
                                            <p>No hay mensajes disponibles.</p>
                                        )}
                                    
                                </tbody>
                            </table>
                            </div>
                            

                        </div>
                    </div>
                </div>
            </div>


        </AuthenticatedLayout>
    );
}
